services:

  db:
    image: postgres:latest
    container_name: bus_station_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bus_station
    ports:
      - "5433:5432"

  cache:
    image: redis:latest
    container_name: bus_station_redis
    ports:
      - "6380:6379"

  docker:
    image: docker:dind
    container_name: docker
    privileged: true
    ports:
      - "2376:2375"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
      - cache
      - docker
    entrypoint: ./docker-entrypoint.sh
    ports:
      - "8082:8081"
