FROM maven:latest as mav
COPY pom.xml /home/homework11/
COPY src /home/homework11/src/
COPY liquibase.properties /home/homework11/
COPY docker-entrypoint.sh /home/homework11/
WORKDIR /home/homework11
