services:

  db:
    image: postgres:latest
    container_name: homework11
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_textnote
    ports:
      - "5433:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    depends_on:
      - db
    volumes:
      - ./H2test/H2test.mv.db:/home/homework11/H2test/H2test.mv.db
      - ./H2test/H2test.trace.db:/home/homework11/H2test/H2test.trace.db
    ports:
      - "8082:8081"
    entrypoint: ./docker-entrypoint.sh
