services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./figures/result.txt:/home/figures/result.txt
    entrypoint: ["java", "-jar", "/home/figures/app.jar"]
