services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./collections/result.json:/home/collections/result.json
    entrypoint: ["java", "-jar", "/home/collections/target/homework07-1.0-SNAPSHOT.jar"]
